python lerobot/scripts/dps_train.py \
    --deepspeed="./ds_zero2_40G.json" \
    --policy.type="pi0" \
    --dataset.root="/mnt/wangxiaofa/robot_dataset/lerobot-format" \
    --dataset.repo_id="any/simulted" \
    --dataset.data_mix="pizza_task_8" \
    --wandb.enable=true \
    --wandb.project="pi0-ft-simulated" \
    --job_name="06-30-pt-pi0-ft-pizza-task8-bs-4-16gpu-gra-acc-2-with-lr-decay-warm-1k-wd-1e-2-1st" \
    --log_dir="/mnt/wangxiaofa/logs" \
    --output_dir="/mnt/wangxiaofa/pi0-ft-simulated/0630-ft-pizza-task8-bs-4-16gpu-gra-acc-2-with-lr-decay-warm-1k-wd-1e-2-1st" \
    --steps=300_000 \
    --dataset.image_transforms.enable=false