python lerobot/scripts/dps_train.py \
    --deepspeed="./ds_zero2.json" \
    --policy.type="pi0" \
    --dataset.root="/mnt/wangxiaofa/robot_dataset/lerobot-format/libero_goal_no_noops_lerobot" \
    --dataset.repo_id="any/simulted" \
    --wandb.enable=true \
    --wandb.project="pi0-ft-simulated" \
    --job_name="pi0-04-14-ft-libero-goal-bs-128-8gpu-gra-acc-4-with-lr-decay-warm-0.25k-lr-3e-6_only-ft-expert-1st" \
    --log_dir="/mnt/wangxiaofa/logs" \
    --output_dir="/mnt/wangxiaofa/pi0-ft-simulated/0414-ft-libero-goal-bs-128-8gpu-gra-acc-4-with-lr-decay-warm-0.25k-lr-3e-6_only-ft-expert-1st" \
    --steps=30_000